---
- name: Network Agnostic Playbook
  hosts: ~^arista
  gather_facts: no 

  tasks: 
  - name: Configure DNS
    cli_config:
      config: ip name-server 8.8.8.8

  - name: Check configuration
    cli_command:
      command: show run | i ip name-server
    register: results

  - name: Print output to screen
    debug:
      var: results.stdout
