---
# tasks file for /home/student/mycode/roles/precheck
- name: Harvest arista facts
  eos_facts:
  when: ansible_network_os == 'eos'

- name: Push to the local system -- by special tag request only
  copy:
    content: "{{ ansible_facts | to_nice_json }}"
    dest: "/home/student/mycode/{{ inventory_hostname }}.txt"

  tags:
    - never
    - grabfacts

- fail:
    msg: "Fail. Network device lacks the correct number of interfaces."
  when: ansible_facts.net_interfaces|length != switchint

- fail:
    msg: "Fail. Network device is running wrong firmware"
  when: "switchver not in ansible_facts.net_version"
